config/routes.rb
Rails.application.routes.draw do
  root "products#index" # トップページを商品一覧に変更
  devise_for :users

  # 公開用製品ページ（認証不要）
  get 'p/:public_id', to: 'public_products#show', as: 'public_product'

  # 企業情報・アカウント管理
  get 'profile', to: 'profiles#show'
  patch 'profile', to: 'profiles#update'

  resources :vendors
  resources :materials do
    collection do
      get :search
    end
    member do
      get 'get_details'
    end
  end
  resources :menus do
    collection do
      post :export_to_sheets
    end
    member do
      get :details
      get :copy
      get :calculate
    end
  end
  resources :products do
    member do
      post :generate_raw_materials # 既存の商品用
      get :copy
      post :regenerate_public_id
    end

    collection do
      post :generate_raw_materials # 新規作成時用
    end
  end
  resources :raw_materials
  resources :daily_menus do
    collection do
      get :material_schedule
    end
    member do
      post :distribute
    end
  end
  resources :stores
  resources :food_ingredients do
    collection do
      get :search
    end
  end
  get 'calendar', to: 'daily_menus#index', as: :calendar

  resources :pdfs do
    collection do
      get :manufacturing_instruction
      get :distribution_instruction
      get :product_recipe
      get :menu_recipe
    end
  end
end

app/models/store.rb
class Store < ApplicationRecord
  include TenantScoped
  
  has_many :store_daily_menu_products, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :company_id }
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[edit update destroy]

  def index
    @stores = company_scope(Store.all)
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    @store.company = current_company
    if @store.save
      redirect_to stores_path, notice: '店舗を作成しました。'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @store.update(store_params)
      redirect_to stores_path, notice: '店舗を更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @store.destroy
    redirect_to stores_path, notice: '店舗を削除しました。'
  end

  private

  def set_store
    @store = company_scope(Store).find(params[:id])
  end

  def store_params
    params.require(:store).permit(:name, :phone, :address, :unused_flag)
  end
end

app/views/stores/_form.html.slim
= form_with(model: store, local: true) do |f|
  .mb-3
    = f.label :name,"店舗名", class: "form-label"
    = f.text_field :name, class: "form-control"

  .mb-3
    = f.label :phone,"電話番号", class: "form-label"
    = f.text_field :phone, class: "form-control"

  .mb-3
    = f.label :address,"住所", class: "form-label"
    = f.text_field :address, class: "form-control"

  .form-check.mb-3
    = f.label :unused_flag, "　使用停止", class: "form-check-label"
    = f.check_box :unused_flag, class: "form-check-input"

  .mt-3
    = f.submit "保存する", class: "btn btn-success"

app/views/stores/edit.html.slim
.container-fluid.py-2.px-3
  .d-flex.justify-content-between.align-items-center.mb-3
    h3.mb-0 店舗編集
    = link_to stores_path, class: "btn btn-outline-secondary" do
      i.bi.bi-arrow-left.me-1
      | 戻る

  = render "form", store: @store

app/views/stores/index.html.slim
.container-fluid.py-4.px-3
  .d-flex.justify-content-between.align-items-center.mb-3
    h3.mb-0 店舗一覧
    = link_to new_store_path, class: "btn btn-primary" do
      i.bi.bi-plus-circle.me-1
      | 新規登録

  .card.shadow-sm.mb-3
    .card-body.py-2.px-3
      .row.g-2
        .col-md-12
          .input-group
            span.input-group-text.py-1
              i.bi.bi-search
            input.form-control.js-store-search type="text" placeholder="店舗名で検索..."

  / デスクトップ用テーブル表示
  .d-none.d-md-block.table-responsive
    table.table.table-hover.table-bordered.mb-0
      thead.table-light
        tr
          th.text-center
          th 名称
          th 電話番号
          th 住所
          th.text-center 状態
      tbody
        - @stores.each do |store|
          tr.js-store-item
            td.text-center
              = link_to edit_store_path(store), class: "btn btn-sm btn-outline-primary" do
                i.bi.bi-pencil
            td = store.name
            td = store.phone
            td = store.address
            td.text-center
              - if store.unused_flag
                span.badge.bg-secondary 停止中
              - else
                span.badge.bg-success 使用中

  / モバイル用カード表示
  .d-md-none
    - @stores.each do |store|
      .card.mb-3.shadow-sm.js-store-item
        .card-body.p-3
          .d-flex.justify-content-between.align-items-start.mb-2
            .fw-bold.mb-1
              = link_to store.name, edit_store_path(store), class: "text-decoration-none"
            - if store.unused_flag
              span.badge.bg-secondary 停止中
            - else
              span.badge.bg-success 使用中
          - if store.phone.present?
            .mb-2
              .small.text-muted 電話番号
              div = store.phone
          - if store.address.present?
            .mb-2
              .small.text-muted 住所
              div = store.address
          .mt-3
            = link_to edit_store_path(store), class: "btn btn-sm btn-outline-primary w-100" do
              i.bi.bi-pencil.me-1
              | 編集

  .d-flex.flex-column.flex-md-row.justify-content-between.align-items-start.align-items-md-center.gap-2.mt-2
    small.text-muted 全 #{@stores.count} 件
    .overflow-auto.w-100.w-md-auto
      = will_paginate @stores, renderer: WillPaginate::ActionView::BootstrapLinkRenderer if @stores.respond_to?(:total_pages)

app/views/stores/new.html.slim
.container-fluid.py-2.px-3
  .d-flex.justify-content-between.align-items-center.mb-3
    h3.mb-0 店舗新規登録
    = link_to stores_path, class: "btn btn-outline-secondary" do
      i.bi.bi-arrow-left.me-1
      | 戻る

  = render "form", store: @store